### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (55,136,102) (3,)

### ISSUE THREAD

**Issue by KMarshallX** [NeuroAI-HD/HD-BET#4]
Hi,

I ran the code with my own data, but it bumped into an error:
```bash
running postprocessing... 
exporting segmentation...
Traceback (most recent call last):
  File "/scratch/itee/uqmxu4/tor_env/bin/hd-bet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/scratch/itee/uqmxu4/HD-BET/HD_BET/hd-bet", line 121, in <module>
    run_hd_bet(input_files, output_files, mode, config_file, device, pp, tta, save_mask, overwrite_existing)
  File "/scratch/itee/uqmxu4/HD-BET/HD_BET/run.py", line 110, in run_hd_bet
    save_segmentation_nifti(seg, data_dict, mask_fname)
  File "/scratch/itee/uqmxu4/HD-BET/HD_BET/data_loading.py", line 87, in save_segmentation_nifti
    if np.any(np.array(seg_old_size) != np.array(dct['size'])[[2, 1, 0]]):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (55,136,102) (3,) 

```

The problem seems to be with line 87, data_loading.py, where you compare a data matrix with a row matrix (the shape). I changed the line to ```if np.any(np.array(seg_old_size).shape != np.array(dct['size'])[[2, 1, 0]]):``` and it ran without errors.

**Comment by ezequieldlrosa** [comment]
I'm having the same issue with an MR image of shape 512x512x29. Any idea how to 'fix' this?
